{% set name = "h2o-wave" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/h2oai/wave/archive/v{{ version }}.tar.gz
  sha256: 48ce4ddde3d8289c09b9a8b7601ca0d2d87c4354f5a3d48bb7aed7c867601034

build:
  entry_points:
    - wave = h2o_wave.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install ./py/h2o_wave -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - arm_pyart
    - hatchling
    - jedi
    - lsprotocol
    - parso
    - playwright-python
    - pygls
    - pytest
    - requests
    - seismon
    - python >={{ python_min }}
    - click
    - httpx >=0.16.1
    - inquirer
    - starlette >=0.13.8
    - uvicorn >=0.17.6

test:
  imports:
    - h2o_wave
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  description: H2O Wave is a lightweight software stack for programming interactive web applications entirely in Python (no HTML/Javascript/CSS required).
  dev_url: https://github.com/h2oai/wave
  doc_url: https://wave.h2o.ai/
  home: https://wave.h2o.ai/
  summary: Python driver for H2O Wave Realtime Apps
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - py/h2o_wave/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
