{% set name = "h2o-wave" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/h2oai/wave/archive/v{{ version }}.tar.gz
  sha256: b72e4fb6f21bb39a104ec6f391ded6f643d9daad6bd7f173c1c65c24b2492798

build:
  entry_points:
    - wave = h2o_wave.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install ./py/h2o_wave -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - click
    - httpx >=0.16.1
    - inquirer
    - starlette >=0.13.8
    - uvicorn >=0.17.6

test:
  imports:
    - h2o_wave
  commands:
    - pip check
  requires:
    - pip

about:
  description: H2O Wave is a lightweight software stack for programming interactive web applications entirely in Python (no HTML/Javascript/CSS required).
  dev_url: https://github.com/h2oai/wave
  doc_url: https://wave.h2o.ai/
  home: https://wave.h2o.ai/
  summary: Python driver for H2O Wave Realtime Apps
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - py/h2o_wave/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
